// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc2
// source: rider.proto

package riderProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiderService_RiderRegister_FullMethodName        = "/rider.RiderService/RiderRegister"
	RiderService_RiderLogin_FullMethodName           = "/rider.RiderService/RiderLogin"
	RiderService_GetRiderInfo_FullMethodName         = "/rider.RiderService/GetRiderInfo"
	RiderService_AcceptOrder_FullMethodName          = "/rider.RiderService/AcceptOrder"
	RiderService_UpdateDeliveryStatus_FullMethodName = "/rider.RiderService/UpdateDeliveryStatus"
	RiderService_ListPendingOrders_FullMethodName    = "/rider.RiderService/ListPendingOrders"
	RiderService_ListRiderOrders_FullMethodName      = "/rider.RiderService/ListRiderOrders"
)

// RiderServiceClient is the client API for RiderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiderServiceClient interface {
	// 骑手注册/入驻
	RiderRegister(ctx context.Context, in *RiderRegisterRequest, opts ...grpc.CallOption) (*RiderRegisterResponse, error)
	// 骑手登录
	RiderLogin(ctx context.Context, in *RiderLoginRequest, opts ...grpc.CallOption) (*RiderLoginResponse, error)
	// 获取骑手信息
	GetRiderInfo(ctx context.Context, in *GetRiderInfoRequest, opts ...grpc.CallOption) (*GetRiderInfoResponse, error)
	// 骑手接单（分配订单）
	AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	// 骑手更新配送状态（取餐/配送中/已完成）
	UpdateDeliveryStatus(ctx context.Context, in *UpdateDeliveryStatusRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	// 骑手查询待接订单列表
	ListPendingOrders(ctx context.Context, in *ListPendingOrdersRequest, opts ...grpc.CallOption) (*ListPendingOrdersResponse, error)
	// 骑手查询自己的配送订单
	ListRiderOrders(ctx context.Context, in *ListRiderOrdersRequest, opts ...grpc.CallOption) (*ListRiderOrdersResponse, error)
}

type riderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRiderServiceClient(cc grpc.ClientConnInterface) RiderServiceClient {
	return &riderServiceClient{cc}
}

func (c *riderServiceClient) RiderRegister(ctx context.Context, in *RiderRegisterRequest, opts ...grpc.CallOption) (*RiderRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiderRegisterResponse)
	err := c.cc.Invoke(ctx, RiderService_RiderRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riderServiceClient) RiderLogin(ctx context.Context, in *RiderLoginRequest, opts ...grpc.CallOption) (*RiderLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiderLoginResponse)
	err := c.cc.Invoke(ctx, RiderService_RiderLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riderServiceClient) GetRiderInfo(ctx context.Context, in *GetRiderInfoRequest, opts ...grpc.CallOption) (*GetRiderInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRiderInfoResponse)
	err := c.cc.Invoke(ctx, RiderService_GetRiderInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riderServiceClient) AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, RiderService_AcceptOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riderServiceClient) UpdateDeliveryStatus(ctx context.Context, in *UpdateDeliveryStatusRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, RiderService_UpdateDeliveryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riderServiceClient) ListPendingOrders(ctx context.Context, in *ListPendingOrdersRequest, opts ...grpc.CallOption) (*ListPendingOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingOrdersResponse)
	err := c.cc.Invoke(ctx, RiderService_ListPendingOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riderServiceClient) ListRiderOrders(ctx context.Context, in *ListRiderOrdersRequest, opts ...grpc.CallOption) (*ListRiderOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRiderOrdersResponse)
	err := c.cc.Invoke(ctx, RiderService_ListRiderOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiderServiceServer is the server API for RiderService service.
// All implementations must embed UnimplementedRiderServiceServer
// for forward compatibility.
type RiderServiceServer interface {
	// 骑手注册/入驻
	RiderRegister(context.Context, *RiderRegisterRequest) (*RiderRegisterResponse, error)
	// 骑手登录
	RiderLogin(context.Context, *RiderLoginRequest) (*RiderLoginResponse, error)
	// 获取骑手信息
	GetRiderInfo(context.Context, *GetRiderInfoRequest) (*GetRiderInfoResponse, error)
	// 骑手接单（分配订单）
	AcceptOrder(context.Context, *AcceptOrderRequest) (*CommonResponse, error)
	// 骑手更新配送状态（取餐/配送中/已完成）
	UpdateDeliveryStatus(context.Context, *UpdateDeliveryStatusRequest) (*CommonResponse, error)
	// 骑手查询待接订单列表
	ListPendingOrders(context.Context, *ListPendingOrdersRequest) (*ListPendingOrdersResponse, error)
	// 骑手查询自己的配送订单
	ListRiderOrders(context.Context, *ListRiderOrdersRequest) (*ListRiderOrdersResponse, error)
	mustEmbedUnimplementedRiderServiceServer()
}

// UnimplementedRiderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiderServiceServer struct{}

func (UnimplementedRiderServiceServer) RiderRegister(context.Context, *RiderRegisterRequest) (*RiderRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RiderRegister not implemented")
}
func (UnimplementedRiderServiceServer) RiderLogin(context.Context, *RiderLoginRequest) (*RiderLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RiderLogin not implemented")
}
func (UnimplementedRiderServiceServer) GetRiderInfo(context.Context, *GetRiderInfoRequest) (*GetRiderInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRiderInfo not implemented")
}
func (UnimplementedRiderServiceServer) AcceptOrder(context.Context, *AcceptOrderRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptOrder not implemented")
}
func (UnimplementedRiderServiceServer) UpdateDeliveryStatus(context.Context, *UpdateDeliveryStatusRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeliveryStatus not implemented")
}
func (UnimplementedRiderServiceServer) ListPendingOrders(context.Context, *ListPendingOrdersRequest) (*ListPendingOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPendingOrders not implemented")
}
func (UnimplementedRiderServiceServer) ListRiderOrders(context.Context, *ListRiderOrdersRequest) (*ListRiderOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRiderOrders not implemented")
}
func (UnimplementedRiderServiceServer) mustEmbedUnimplementedRiderServiceServer() {}
func (UnimplementedRiderServiceServer) testEmbeddedByValue()                      {}

// UnsafeRiderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiderServiceServer will
// result in compilation errors.
type UnsafeRiderServiceServer interface {
	mustEmbedUnimplementedRiderServiceServer()
}

func RegisterRiderServiceServer(s grpc.ServiceRegistrar, srv RiderServiceServer) {
	// If the following call pancis, it indicates UnimplementedRiderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiderService_ServiceDesc, srv)
}

func _RiderService_RiderRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiderRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiderServiceServer).RiderRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiderService_RiderRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiderServiceServer).RiderRegister(ctx, req.(*RiderRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiderService_RiderLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiderLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiderServiceServer).RiderLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiderService_RiderLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiderServiceServer).RiderLogin(ctx, req.(*RiderLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiderService_GetRiderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiderInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiderServiceServer).GetRiderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiderService_GetRiderInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiderServiceServer).GetRiderInfo(ctx, req.(*GetRiderInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiderService_AcceptOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiderServiceServer).AcceptOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiderService_AcceptOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiderServiceServer).AcceptOrder(ctx, req.(*AcceptOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiderService_UpdateDeliveryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeliveryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiderServiceServer).UpdateDeliveryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiderService_UpdateDeliveryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiderServiceServer).UpdateDeliveryStatus(ctx, req.(*UpdateDeliveryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiderService_ListPendingOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiderServiceServer).ListPendingOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiderService_ListPendingOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiderServiceServer).ListPendingOrders(ctx, req.(*ListPendingOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiderService_ListRiderOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRiderOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiderServiceServer).ListRiderOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiderService_ListRiderOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiderServiceServer).ListRiderOrders(ctx, req.(*ListRiderOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiderService_ServiceDesc is the grpc.ServiceDesc for RiderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rider.RiderService",
	HandlerType: (*RiderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RiderRegister",
			Handler:    _RiderService_RiderRegister_Handler,
		},
		{
			MethodName: "RiderLogin",
			Handler:    _RiderService_RiderLogin_Handler,
		},
		{
			MethodName: "GetRiderInfo",
			Handler:    _RiderService_GetRiderInfo_Handler,
		},
		{
			MethodName: "AcceptOrder",
			Handler:    _RiderService_AcceptOrder_Handler,
		},
		{
			MethodName: "UpdateDeliveryStatus",
			Handler:    _RiderService_UpdateDeliveryStatus_Handler,
		},
		{
			MethodName: "ListPendingOrders",
			Handler:    _RiderService_ListPendingOrders_Handler,
		},
		{
			MethodName: "ListRiderOrders",
			Handler:    _RiderService_ListRiderOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rider.proto",
}
