// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0--rc2
// source: rider.proto

package riderProto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 骑手基础信息
type Rider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       int64                  `protobuf:"varint,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`          // 骑手ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                // 骑手姓名
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`                              // 骑手电话
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`                            // 骑手头像
	Score         float32                `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`                            // 骑手评分
	OrderCount    int32                  `protobuf:"varint,6,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"` // 配送订单数
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                            // 骑手状态：在线/离线/休息
	CreateTime    string                 `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`  // 创建时间
	UpdateTime    string                 `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`  // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rider) Reset() {
	*x = Rider{}
	mi := &file_rider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rider) ProtoMessage() {}

func (x *Rider) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rider.ProtoReflect.Descriptor instead.
func (*Rider) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{0}
}

func (x *Rider) GetRiderId() int64 {
	if x != nil {
		return x.RiderId
	}
	return 0
}

func (x *Rider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rider) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Rider) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Rider) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Rider) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *Rider) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Rider) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Rider) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

// 配送订单信息
type DeliveryOrder struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                     // 订单ID
	OrderNo        string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`                      // 订单编号
	RiderId        int64                  `protobuf:"varint,3,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`                     // 骑手ID
	RiderName      string                 `protobuf:"bytes,4,opt,name=rider_name,json=riderName,proto3" json:"rider_name,omitempty"`                // 骑手姓名
	MerchantId     int64                  `protobuf:"varint,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`            // 商家ID
	MerchantName   string                 `protobuf:"bytes,6,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`       // 商家名称
	Address        string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`                                     // 配送地址
	TotalAmount    float32                `protobuf:"fixed32,8,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`        // 订单金额
	DeliveryStatus string                 `protobuf:"bytes,9,opt,name=delivery_status,json=deliveryStatus,proto3" json:"delivery_status,omitempty"` // 配送状态：待取餐/配送中/已完成/已取消
	AcceptTime     string                 `protobuf:"bytes,10,opt,name=accept_time,json=acceptTime,proto3" json:"accept_time,omitempty"`            // 接单时间
	PickupTime     string                 `protobuf:"bytes,11,opt,name=pickup_time,json=pickupTime,proto3" json:"pickup_time,omitempty"`            // 取餐时间
	CompleteTime   string                 `protobuf:"bytes,12,opt,name=complete_time,json=completeTime,proto3" json:"complete_time,omitempty"`      // 完成时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeliveryOrder) Reset() {
	*x = DeliveryOrder{}
	mi := &file_rider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryOrder) ProtoMessage() {}

func (x *DeliveryOrder) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryOrder.ProtoReflect.Descriptor instead.
func (*DeliveryOrder) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{1}
}

func (x *DeliveryOrder) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *DeliveryOrder) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *DeliveryOrder) GetRiderId() int64 {
	if x != nil {
		return x.RiderId
	}
	return 0
}

func (x *DeliveryOrder) GetRiderName() string {
	if x != nil {
		return x.RiderName
	}
	return ""
}

func (x *DeliveryOrder) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *DeliveryOrder) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *DeliveryOrder) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DeliveryOrder) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *DeliveryOrder) GetDeliveryStatus() string {
	if x != nil {
		return x.DeliveryStatus
	}
	return ""
}

func (x *DeliveryOrder) GetAcceptTime() string {
	if x != nil {
		return x.AcceptTime
	}
	return ""
}

func (x *DeliveryOrder) GetPickupTime() string {
	if x != nil {
		return x.PickupTime
	}
	return ""
}

func (x *DeliveryOrder) GetCompleteTime() string {
	if x != nil {
		return x.CompleteTime
	}
	return ""
}

// 通用响应
type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_rider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{2}
}

func (x *CommonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 骑手注册请求
type RiderRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderRegisterRequest) Reset() {
	*x = RiderRegisterRequest{}
	mi := &file_rider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderRegisterRequest) ProtoMessage() {}

func (x *RiderRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderRegisterRequest.ProtoReflect.Descriptor instead.
func (*RiderRegisterRequest) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{3}
}

func (x *RiderRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RiderRegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RiderRegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RiderRegisterRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// 骑手注册响应
type RiderRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	RiderId       int64                  `protobuf:"varint,3,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderRegisterResponse) Reset() {
	*x = RiderRegisterResponse{}
	mi := &file_rider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderRegisterResponse) ProtoMessage() {}

func (x *RiderRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderRegisterResponse.ProtoReflect.Descriptor instead.
func (*RiderRegisterResponse) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{4}
}

func (x *RiderRegisterResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RiderRegisterResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RiderRegisterResponse) GetRiderId() int64 {
	if x != nil {
		return x.RiderId
	}
	return 0
}

func (x *RiderRegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 骑手登录请求
type RiderLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderLoginRequest) Reset() {
	*x = RiderLoginRequest{}
	mi := &file_rider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderLoginRequest) ProtoMessage() {}

func (x *RiderLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderLoginRequest.ProtoReflect.Descriptor instead.
func (*RiderLoginRequest) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{5}
}

func (x *RiderLoginRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RiderLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 骑手登录响应
type RiderLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	RiderId       int64                  `protobuf:"varint,3,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderLoginResponse) Reset() {
	*x = RiderLoginResponse{}
	mi := &file_rider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderLoginResponse) ProtoMessage() {}

func (x *RiderLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderLoginResponse.ProtoReflect.Descriptor instead.
func (*RiderLoginResponse) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{6}
}

func (x *RiderLoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RiderLoginResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RiderLoginResponse) GetRiderId() int64 {
	if x != nil {
		return x.RiderId
	}
	return 0
}

func (x *RiderLoginResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RiderLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取骑手信息请求
type GetRiderInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       int64                  `protobuf:"varint,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiderInfoRequest) Reset() {
	*x = GetRiderInfoRequest{}
	mi := &file_rider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiderInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiderInfoRequest) ProtoMessage() {}

func (x *GetRiderInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiderInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRiderInfoRequest) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{7}
}

func (x *GetRiderInfoRequest) GetRiderId() int64 {
	if x != nil {
		return x.RiderId
	}
	return 0
}

// 获取骑手信息响应
type GetRiderInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Rider         *Rider                 `protobuf:"bytes,3,opt,name=rider,proto3" json:"rider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiderInfoResponse) Reset() {
	*x = GetRiderInfoResponse{}
	mi := &file_rider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiderInfoResponse) ProtoMessage() {}

func (x *GetRiderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiderInfoResponse.ProtoReflect.Descriptor instead.
func (*GetRiderInfoResponse) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{8}
}

func (x *GetRiderInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRiderInfoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetRiderInfoResponse) GetRider() *Rider {
	if x != nil {
		return x.Rider
	}
	return nil
}

// 骑手接单请求
type AcceptOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	RiderId       int64                  `protobuf:"varint,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOrderRequest) Reset() {
	*x = AcceptOrderRequest{}
	mi := &file_rider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderRequest) ProtoMessage() {}

func (x *AcceptOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderRequest.ProtoReflect.Descriptor instead.
func (*AcceptOrderRequest) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{9}
}

func (x *AcceptOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *AcceptOrderRequest) GetRiderId() int64 {
	if x != nil {
		return x.RiderId
	}
	return 0
}

// 更新配送状态请求
type UpdateDeliveryStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	RiderId        int64                  `protobuf:"varint,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DeliveryStatus string                 `protobuf:"bytes,3,opt,name=delivery_status,json=deliveryStatus,proto3" json:"delivery_status,omitempty"`
	Time           string                 `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"` // 状态变更时间（取餐/完成时间）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateDeliveryStatusRequest) Reset() {
	*x = UpdateDeliveryStatusRequest{}
	mi := &file_rider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryStatusRequest) ProtoMessage() {}

func (x *UpdateDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateDeliveryStatusRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UpdateDeliveryStatusRequest) GetRiderId() int64 {
	if x != nil {
		return x.RiderId
	}
	return 0
}

func (x *UpdateDeliveryStatusRequest) GetDeliveryStatus() string {
	if x != nil {
		return x.DeliveryStatus
	}
	return ""
}

func (x *UpdateDeliveryStatusRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

// 查询待接订单列表请求
type ListPendingOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Area          string                 `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"` // 配送区域（可选）
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingOrdersRequest) Reset() {
	*x = ListPendingOrdersRequest{}
	mi := &file_rider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingOrdersRequest) ProtoMessage() {}

func (x *ListPendingOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListPendingOrdersRequest) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{11}
}

func (x *ListPendingOrdersRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *ListPendingOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPendingOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 查询待接订单列表响应
type ListPendingOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Orders        []*DeliveryOrder       `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingOrdersResponse) Reset() {
	*x = ListPendingOrdersResponse{}
	mi := &file_rider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingOrdersResponse) ProtoMessage() {}

func (x *ListPendingOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListPendingOrdersResponse) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{12}
}

func (x *ListPendingOrdersResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListPendingOrdersResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListPendingOrdersResponse) GetOrders() []*DeliveryOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListPendingOrdersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPendingOrdersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPendingOrdersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 查询骑手配送订单请求
type ListRiderOrdersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RiderId        int64                  `protobuf:"varint,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DeliveryStatus string                 `protobuf:"bytes,2,opt,name=delivery_status,json=deliveryStatus,proto3" json:"delivery_status,omitempty"` // 配送状态（可选）
	Page           int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListRiderOrdersRequest) Reset() {
	*x = ListRiderOrdersRequest{}
	mi := &file_rider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRiderOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRiderOrdersRequest) ProtoMessage() {}

func (x *ListRiderOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRiderOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListRiderOrdersRequest) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{13}
}

func (x *ListRiderOrdersRequest) GetRiderId() int64 {
	if x != nil {
		return x.RiderId
	}
	return 0
}

func (x *ListRiderOrdersRequest) GetDeliveryStatus() string {
	if x != nil {
		return x.DeliveryStatus
	}
	return ""
}

func (x *ListRiderOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRiderOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 查询骑手配送订单响应
type ListRiderOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Orders        []*DeliveryOrder       `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRiderOrdersResponse) Reset() {
	*x = ListRiderOrdersResponse{}
	mi := &file_rider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRiderOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRiderOrdersResponse) ProtoMessage() {}

func (x *ListRiderOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRiderOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListRiderOrdersResponse) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{14}
}

func (x *ListRiderOrdersResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListRiderOrdersResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListRiderOrdersResponse) GetOrders() []*DeliveryOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListRiderOrdersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListRiderOrdersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRiderOrdersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_rider_proto protoreflect.FileDescriptor

const file_rider_proto_rawDesc = "" +
	"\n" +
	"\vrider.proto\x12\x05rider\x1a\x0evalidate.proto\"\xf5\x01\n" +
	"\x05Rider\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\x03R\ariderId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x02R\x05score\x12\x1f\n" +
	"\vorder_count\x18\x06 \x01(\x05R\n" +
	"orderCount\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\t \x01(\tR\n" +
	"updateTime\"\x92\x03\n" +
	"\rDeliveryOrder\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x19\n" +
	"\brider_id\x18\x03 \x01(\x03R\ariderId\x12\x1d\n" +
	"\n" +
	"rider_name\x18\x04 \x01(\tR\triderName\x12\x1f\n" +
	"\vmerchant_id\x18\x05 \x01(\x03R\n" +
	"merchantId\x12#\n" +
	"\rmerchant_name\x18\x06 \x01(\tR\fmerchantName\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12!\n" +
	"\ftotal_amount\x18\b \x01(\x02R\vtotalAmount\x12'\n" +
	"\x0fdelivery_status\x18\t \x01(\tR\x0edeliveryStatus\x12\x1f\n" +
	"\vaccept_time\x18\n" +
	" \x01(\tR\n" +
	"acceptTime\x12\x1f\n" +
	"\vpickup_time\x18\v \x01(\tR\n" +
	"pickupTime\x12#\n" +
	"\rcomplete_time\x18\f \x01(\tR\fcompleteTime\"6\n" +
	"\x0eCommonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xa6\x01\n" +
	"\x14RiderRegisterRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x02R\x04name\x12*\n" +
	"\x05phone\x18\x02 \x01(\tB\x14\xfaB\x11r\x0f2\r^1[3-9]\\d{9}$R\x05phone\x12#\n" +
	"\bpassword\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x06R\bpassword\x12 \n" +
	"\x06avatar\x18\x04 \x01(\tB\b\xfaB\x05r\x03\x88\x01\x01R\x06avatar\"n\n" +
	"\x15RiderRegisterResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x19\n" +
	"\brider_id\x18\x03 \x01(\x03R\ariderId\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"d\n" +
	"\x11RiderLoginRequest\x12*\n" +
	"\x05phone\x18\x01 \x01(\tB\x14\xfaB\x11r\x0f2\r^1[3-9]\\d{9}$R\x05phone\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x06R\bpassword\"\x7f\n" +
	"\x12RiderLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x19\n" +
	"\brider_id\x18\x03 \x01(\x03R\ariderId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\"9\n" +
	"\x13GetRiderInfoRequest\x12\"\n" +
	"\brider_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\ariderId\"`\n" +
	"\x14GetRiderInfoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\"\n" +
	"\x05rider\x18\x03 \x01(\v2\f.rider.RiderR\x05rider\"\\\n" +
	"\x12AcceptOrderRequest\x12\"\n" +
	"\border_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aorderId\x12\"\n" +
	"\brider_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\ariderId\"\xab\x01\n" +
	"\x1bUpdateDeliveryStatusRequest\x12\"\n" +
	"\border_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aorderId\x12\"\n" +
	"\brider_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\ariderId\x120\n" +
	"\x0fdelivery_status\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x02R\x0edeliveryStatus\x12\x12\n" +
	"\x04time\x18\x04 \x01(\tR\x04time\"s\n" +
	"\x18ListPendingOrdersRequest\x12\x12\n" +
	"\x04area\x18\x01 \x01(\tR\x04area\x12\x1b\n" +
	"\x04page\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x04page\x12&\n" +
	"\tpage_size\x18\x03 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\n" +
	"R\bpageSize\"\xb6\x01\n" +
	"\x19ListPendingOrdersResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12,\n" +
	"\x06orders\x18\x03 \x03(\v2\x14.rider.DeliveryOrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\xaa\x01\n" +
	"\x16ListRiderOrdersRequest\x12\"\n" +
	"\brider_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\ariderId\x12'\n" +
	"\x0fdelivery_status\x18\x02 \x01(\tR\x0edeliveryStatus\x12\x1b\n" +
	"\x04page\x18\x03 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x04page\x12&\n" +
	"\tpage_size\x18\x04 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\n" +
	"R\bpageSize\"\xb4\x01\n" +
	"\x17ListRiderOrdersResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12,\n" +
	"\x06orders\x18\x03 \x03(\v2\x14.rider.DeliveryOrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize2\xa4\x04\n" +
	"\fRiderService\x12J\n" +
	"\rRiderRegister\x12\x1b.rider.RiderRegisterRequest\x1a\x1c.rider.RiderRegisterResponse\x12A\n" +
	"\n" +
	"RiderLogin\x12\x18.rider.RiderLoginRequest\x1a\x19.rider.RiderLoginResponse\x12G\n" +
	"\fGetRiderInfo\x12\x1a.rider.GetRiderInfoRequest\x1a\x1b.rider.GetRiderInfoResponse\x12?\n" +
	"\vAcceptOrder\x12\x19.rider.AcceptOrderRequest\x1a\x15.rider.CommonResponse\x12Q\n" +
	"\x14UpdateDeliveryStatus\x12\".rider.UpdateDeliveryStatusRequest\x1a\x15.rider.CommonResponse\x12V\n" +
	"\x11ListPendingOrders\x12\x1f.rider.ListPendingOrdersRequest\x1a .rider.ListPendingOrdersResponse\x12P\n" +
	"\x0fListRiderOrders\x12\x1d.rider.ListRiderOrdersRequest\x1a\x1e.rider.ListRiderOrdersResponseB#Z!./internal/rider/proto;riderProtob\x06proto3"

var (
	file_rider_proto_rawDescOnce sync.Once
	file_rider_proto_rawDescData []byte
)

func file_rider_proto_rawDescGZIP() []byte {
	file_rider_proto_rawDescOnce.Do(func() {
		file_rider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rider_proto_rawDesc), len(file_rider_proto_rawDesc)))
	})
	return file_rider_proto_rawDescData
}

var file_rider_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_rider_proto_goTypes = []any{
	(*Rider)(nil),                       // 0: rider.Rider
	(*DeliveryOrder)(nil),               // 1: rider.DeliveryOrder
	(*CommonResponse)(nil),              // 2: rider.CommonResponse
	(*RiderRegisterRequest)(nil),        // 3: rider.RiderRegisterRequest
	(*RiderRegisterResponse)(nil),       // 4: rider.RiderRegisterResponse
	(*RiderLoginRequest)(nil),           // 5: rider.RiderLoginRequest
	(*RiderLoginResponse)(nil),          // 6: rider.RiderLoginResponse
	(*GetRiderInfoRequest)(nil),         // 7: rider.GetRiderInfoRequest
	(*GetRiderInfoResponse)(nil),        // 8: rider.GetRiderInfoResponse
	(*AcceptOrderRequest)(nil),          // 9: rider.AcceptOrderRequest
	(*UpdateDeliveryStatusRequest)(nil), // 10: rider.UpdateDeliveryStatusRequest
	(*ListPendingOrdersRequest)(nil),    // 11: rider.ListPendingOrdersRequest
	(*ListPendingOrdersResponse)(nil),   // 12: rider.ListPendingOrdersResponse
	(*ListRiderOrdersRequest)(nil),      // 13: rider.ListRiderOrdersRequest
	(*ListRiderOrdersResponse)(nil),     // 14: rider.ListRiderOrdersResponse
}
var file_rider_proto_depIdxs = []int32{
	0,  // 0: rider.GetRiderInfoResponse.rider:type_name -> rider.Rider
	1,  // 1: rider.ListPendingOrdersResponse.orders:type_name -> rider.DeliveryOrder
	1,  // 2: rider.ListRiderOrdersResponse.orders:type_name -> rider.DeliveryOrder
	3,  // 3: rider.RiderService.RiderRegister:input_type -> rider.RiderRegisterRequest
	5,  // 4: rider.RiderService.RiderLogin:input_type -> rider.RiderLoginRequest
	7,  // 5: rider.RiderService.GetRiderInfo:input_type -> rider.GetRiderInfoRequest
	9,  // 6: rider.RiderService.AcceptOrder:input_type -> rider.AcceptOrderRequest
	10, // 7: rider.RiderService.UpdateDeliveryStatus:input_type -> rider.UpdateDeliveryStatusRequest
	11, // 8: rider.RiderService.ListPendingOrders:input_type -> rider.ListPendingOrdersRequest
	13, // 9: rider.RiderService.ListRiderOrders:input_type -> rider.ListRiderOrdersRequest
	4,  // 10: rider.RiderService.RiderRegister:output_type -> rider.RiderRegisterResponse
	6,  // 11: rider.RiderService.RiderLogin:output_type -> rider.RiderLoginResponse
	8,  // 12: rider.RiderService.GetRiderInfo:output_type -> rider.GetRiderInfoResponse
	2,  // 13: rider.RiderService.AcceptOrder:output_type -> rider.CommonResponse
	2,  // 14: rider.RiderService.UpdateDeliveryStatus:output_type -> rider.CommonResponse
	12, // 15: rider.RiderService.ListPendingOrders:output_type -> rider.ListPendingOrdersResponse
	14, // 16: rider.RiderService.ListRiderOrders:output_type -> rider.ListRiderOrdersResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_rider_proto_init() }
func file_rider_proto_init() {
	if File_rider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rider_proto_rawDesc), len(file_rider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rider_proto_goTypes,
		DependencyIndexes: file_rider_proto_depIdxs,
		MessageInfos:      file_rider_proto_msgTypes,
	}.Build()
	File_rider_proto = out.File
	file_rider_proto_goTypes = nil
	file_rider_proto_depIdxs = nil
}
