// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0--rc2
// source: merchant.proto

package merchantProto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商家信息
type Merchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int64                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`         // 商家ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                        // 商家名称
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`                                      // 商家电话
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`                                // 密码（加密后，前端不返回）
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`                                  // 商家地址
	Logo          string                 `protobuf:"bytes,6,opt,name=logo,proto3" json:"logo,omitempty"`                                        // 商家logo
	BusinessHours string                 `protobuf:"bytes,7,opt,name=business_hours,json=businessHours,proto3" json:"business_hours,omitempty"` // 营业时间
	Score         float32                `protobuf:"fixed32,8,opt,name=score,proto3" json:"score,omitempty"`                                    // 商家评分（默认5.0）
	OrderCount    int32                  `protobuf:"varint,9,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`         // 订单数
	IsOpen        bool                   `protobuf:"varint,10,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`                    // 是否营业
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`            // 创建时间
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`            // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Merchant) Reset() {
	*x = Merchant{}
	mi := &file_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Merchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merchant) ProtoMessage() {}

func (x *Merchant) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merchant.ProtoReflect.Descriptor instead.
func (*Merchant) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *Merchant) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *Merchant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Merchant) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Merchant) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Merchant) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Merchant) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *Merchant) GetBusinessHours() string {
	if x != nil {
		return x.BusinessHours
	}
	return ""
}

func (x *Merchant) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Merchant) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *Merchant) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *Merchant) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Merchant) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 订单简要信息（商家端）
type MerchantOrder struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrderId            int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                                   // 订单ID
	UserId             int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                      // 用户ID
	UserName           string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`                                 // 用户名
	UserPhone          string                 `protobuf:"bytes,4,opt,name=user_phone,json=userPhone,proto3" json:"user_phone,omitempty"`                              // 用户电话
	TotalAmount        float32                `protobuf:"fixed32,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`                      // 订单总金额
	Status             string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                                     // 订单状态
	CreateTime         string                 `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                           // 创建时间
	ExpectDeliveryTime string                 `protobuf:"bytes,8,opt,name=expect_delivery_time,json=expectDeliveryTime,proto3" json:"expect_delivery_time,omitempty"` // 预计送达时间
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MerchantOrder) Reset() {
	*x = MerchantOrder{}
	mi := &file_merchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantOrder) ProtoMessage() {}

func (x *MerchantOrder) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantOrder.ProtoReflect.Descriptor instead.
func (*MerchantOrder) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{1}
}

func (x *MerchantOrder) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *MerchantOrder) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MerchantOrder) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MerchantOrder) GetUserPhone() string {
	if x != nil {
		return x.UserPhone
	}
	return ""
}

func (x *MerchantOrder) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *MerchantOrder) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MerchantOrder) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *MerchantOrder) GetExpectDeliveryTime() string {
	if x != nil {
		return x.ExpectDeliveryTime
	}
	return ""
}

// 通用响应
type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_merchant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{2}
}

func (x *CommonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 商家注册请求
type MerchantRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Logo          string                 `protobuf:"bytes,5,opt,name=logo,proto3" json:"logo,omitempty"`
	BusinessHours string                 `protobuf:"bytes,6,opt,name=business_hours,json=businessHours,proto3" json:"business_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantRegisterRequest) Reset() {
	*x = MerchantRegisterRequest{}
	mi := &file_merchant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantRegisterRequest) ProtoMessage() {}

func (x *MerchantRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantRegisterRequest.ProtoReflect.Descriptor instead.
func (*MerchantRegisterRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{3}
}

func (x *MerchantRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MerchantRegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *MerchantRegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *MerchantRegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MerchantRegisterRequest) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *MerchantRegisterRequest) GetBusinessHours() string {
	if x != nil {
		return x.BusinessHours
	}
	return ""
}

// 商家注册响应
type MerchantRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	MerchantId    int64                  `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantRegisterResponse) Reset() {
	*x = MerchantRegisterResponse{}
	mi := &file_merchant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantRegisterResponse) ProtoMessage() {}

func (x *MerchantRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantRegisterResponse.ProtoReflect.Descriptor instead.
func (*MerchantRegisterResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{4}
}

func (x *MerchantRegisterResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MerchantRegisterResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MerchantRegisterResponse) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *MerchantRegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 商家登录请求
type MerchantLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantLoginRequest) Reset() {
	*x = MerchantLoginRequest{}
	mi := &file_merchant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantLoginRequest) ProtoMessage() {}

func (x *MerchantLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantLoginRequest.ProtoReflect.Descriptor instead.
func (*MerchantLoginRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{5}
}

func (x *MerchantLoginRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *MerchantLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 商家登录响应
type MerchantLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	MerchantId    int64                  `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantLoginResponse) Reset() {
	*x = MerchantLoginResponse{}
	mi := &file_merchant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantLoginResponse) ProtoMessage() {}

func (x *MerchantLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantLoginResponse.ProtoReflect.Descriptor instead.
func (*MerchantLoginResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{6}
}

func (x *MerchantLoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MerchantLoginResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MerchantLoginResponse) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *MerchantLoginResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MerchantLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取商家信息请求
type GetMerchantInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int64                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantInfoRequest) Reset() {
	*x = GetMerchantInfoRequest{}
	mi := &file_merchant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantInfoRequest) ProtoMessage() {}

func (x *GetMerchantInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantInfoRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{7}
}

func (x *GetMerchantInfoRequest) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

// 获取商家信息响应
type GetMerchantInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Merchant      *Merchant              `protobuf:"bytes,3,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantInfoResponse) Reset() {
	*x = GetMerchantInfoResponse{}
	mi := &file_merchant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantInfoResponse) ProtoMessage() {}

func (x *GetMerchantInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantInfoResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantInfoResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{8}
}

func (x *GetMerchantInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetMerchantInfoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetMerchantInfoResponse) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

// 更新商家信息请求
type UpdateMerchantInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int64                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Logo          string                 `protobuf:"bytes,5,opt,name=logo,proto3" json:"logo,omitempty"`
	BusinessHours string                 `protobuf:"bytes,6,opt,name=business_hours,json=businessHours,proto3" json:"business_hours,omitempty"`
	IsOpen        bool                   `protobuf:"varint,7,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMerchantInfoRequest) Reset() {
	*x = UpdateMerchantInfoRequest{}
	mi := &file_merchant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantInfoRequest) ProtoMessage() {}

func (x *UpdateMerchantInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantInfoRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMerchantInfoRequest) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *UpdateMerchantInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMerchantInfoRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateMerchantInfoRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateMerchantInfoRequest) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *UpdateMerchantInfoRequest) GetBusinessHours() string {
	if x != nil {
		return x.BusinessHours
	}
	return ""
}

func (x *UpdateMerchantInfoRequest) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

// 接单请求
type AcceptOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	MerchantId    int64                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOrderRequest) Reset() {
	*x = AcceptOrderRequest{}
	mi := &file_merchant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderRequest) ProtoMessage() {}

func (x *AcceptOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderRequest.ProtoReflect.Descriptor instead.
func (*AcceptOrderRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{10}
}

func (x *AcceptOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *AcceptOrderRequest) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

// 拒单请求
type RejectOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	MerchantId    int64                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectOrderRequest) Reset() {
	*x = RejectOrderRequest{}
	mi := &file_merchant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectOrderRequest) ProtoMessage() {}

func (x *RejectOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectOrderRequest.ProtoReflect.Descriptor instead.
func (*RejectOrderRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{11}
}

func (x *RejectOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *RejectOrderRequest) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *RejectOrderRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 查询商家订单列表请求
type ListMerchantOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int64                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // 订单状态（可选，空表示所有）
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantOrdersRequest) Reset() {
	*x = ListMerchantOrdersRequest{}
	mi := &file_merchant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantOrdersRequest) ProtoMessage() {}

func (x *ListMerchantOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListMerchantOrdersRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{12}
}

func (x *ListMerchantOrdersRequest) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *ListMerchantOrdersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListMerchantOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMerchantOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 查询商家订单列表响应
type ListMerchantOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Orders        []*MerchantOrder       `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantOrdersResponse) Reset() {
	*x = ListMerchantOrdersResponse{}
	mi := &file_merchant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantOrdersResponse) ProtoMessage() {}

func (x *ListMerchantOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListMerchantOrdersResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{13}
}

func (x *ListMerchantOrdersResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListMerchantOrdersResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListMerchantOrdersResponse) GetOrders() []*MerchantOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListMerchantOrdersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListMerchantOrdersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMerchantOrdersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_merchant_proto protoreflect.FileDescriptor

const file_merchant_proto_rawDesc = "" +
	"\n" +
	"\x0emerchant.proto\x12\bmerchant\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0evalidate.proto\"\xd4\x02\n" +
	"\bMerchant\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x03R\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x12\n" +
	"\x04logo\x18\x06 \x01(\tR\x04logo\x12%\n" +
	"\x0ebusiness_hours\x18\a \x01(\tR\rbusinessHours\x12\x14\n" +
	"\x05score\x18\b \x01(\x02R\x05score\x12\x1f\n" +
	"\vorder_count\x18\t \x01(\x05R\n" +
	"orderCount\x12\x17\n" +
	"\ais_open\x18\n" +
	" \x01(\bR\x06isOpen\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\x8d\x02\n" +
	"\rMerchantOrder\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"user_phone\x18\x04 \x01(\tR\tuserPhone\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x02R\vtotalAmount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\tR\n" +
	"createTime\x120\n" +
	"\x14expect_delivery_time\x18\b \x01(\tR\x12expectDeliveryTime\"6\n" +
	"\x0eCommonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xff\x01\n" +
	"\x17MerchantRegisterRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x02\x18@R\x04name\x12*\n" +
	"\x05phone\x18\x02 \x01(\tB\x14\xfaB\x11r\x0f2\r^1[3-9]\\d{9}$R\x05phone\x12%\n" +
	"\bpassword\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x06\x18\x14R\bpassword\x12$\n" +
	"\aaddress\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x05\x18\xff\x01R\aaddress\x12\x1c\n" +
	"\x04logo\x18\x05 \x01(\tB\b\xfaB\x05r\x03\x88\x01\x01R\x04logo\x12.\n" +
	"\x0ebusiness_hours\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x10\x05R\rbusinessHours\"w\n" +
	"\x18MerchantRegisterResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x03R\n" +
	"merchantId\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"i\n" +
	"\x14MerchantLoginRequest\x12*\n" +
	"\x05phone\x18\x01 \x01(\tB\x14\xfaB\x11r\x0f2\r^1[3-9]\\d{9}$R\x05phone\x12%\n" +
	"\bpassword\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x06\x18\x14R\bpassword\"\x88\x01\n" +
	"\x15MerchantLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x03R\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\"B\n" +
	"\x16GetMerchantInfoRequest\x12(\n" +
	"\vmerchant_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\n" +
	"merchantId\"o\n" +
	"\x17GetMerchantInfoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12.\n" +
	"\bmerchant\x18\x03 \x01(\v2\x12.merchant.MerchantR\bmerchant\"\xa6\x02\n" +
	"\x19UpdateMerchantInfoRequest\x12(\n" +
	"\vmerchant_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\n" +
	"merchantId\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x02\x18@R\x04name\x12*\n" +
	"\x05phone\x18\x03 \x01(\tB\x14\xfaB\x11r\x0f2\r^1[3-9]\\d{9}$R\x05phone\x12$\n" +
	"\aaddress\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x05\x18\xff\x01R\aaddress\x12\x1c\n" +
	"\x04logo\x18\x05 \x01(\tB\b\xfaB\x05r\x03\x88\x01\x01R\x04logo\x12.\n" +
	"\x0ebusiness_hours\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x10\x05R\rbusinessHours\x12 \n" +
	"\ais_open\x18\a \x01(\bB\a\xfaB\x04j\x02\b\x01R\x06isOpen\"b\n" +
	"\x12AcceptOrderRequest\x12\"\n" +
	"\border_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aorderId\x12(\n" +
	"\vmerchant_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\n" +
	"merchantId\"\x86\x01\n" +
	"\x12RejectOrderRequest\x12\"\n" +
	"\border_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aorderId\x12(\n" +
	"\vmerchant_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\n" +
	"merchantId\x12\"\n" +
	"\x06reason\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x02\x18\x80\x01R\x06reason\"\xa2\x01\n" +
	"\x19ListMerchantOrdersRequest\x12(\n" +
	"\vmerchant_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\n" +
	"merchantId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\x04page\x18\x03 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x04page\x12&\n" +
	"\tpage_size\x18\x04 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\n" +
	"R\bpageSize\"\xba\x01\n" +
	"\x1aListMerchantOrdersResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12/\n" +
	"\x06orders\x18\x03 \x03(\v2\x17.merchant.MerchantOrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize2\xda\x04\n" +
	"\x0fMerchantService\x12Y\n" +
	"\x10MerchantRegister\x12!.merchant.MerchantRegisterRequest\x1a\".merchant.MerchantRegisterResponse\x12P\n" +
	"\rMerchantLogin\x12\x1e.merchant.MerchantLoginRequest\x1a\x1f.merchant.MerchantLoginResponse\x12V\n" +
	"\x0fGetMerchantInfo\x12 .merchant.GetMerchantInfoRequest\x1a!.merchant.GetMerchantInfoResponse\x12S\n" +
	"\x12UpdateMerchantInfo\x12#.merchant.UpdateMerchantInfoRequest\x1a\x18.merchant.CommonResponse\x12E\n" +
	"\vAcceptOrder\x12\x1c.merchant.AcceptOrderRequest\x1a\x18.merchant.CommonResponse\x12E\n" +
	"\vRejectOrder\x12\x1c.merchant.RejectOrderRequest\x1a\x18.merchant.CommonResponse\x12_\n" +
	"\x12ListMerchantOrders\x12#.merchant.ListMerchantOrdersRequest\x1a$.merchant.ListMerchantOrdersResponseB)Z'./internal/merchant/proto;merchantProtob\x06proto3"

var (
	file_merchant_proto_rawDescOnce sync.Once
	file_merchant_proto_rawDescData []byte
)

func file_merchant_proto_rawDescGZIP() []byte {
	file_merchant_proto_rawDescOnce.Do(func() {
		file_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_proto_rawDesc), len(file_merchant_proto_rawDesc)))
	})
	return file_merchant_proto_rawDescData
}

var file_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_merchant_proto_goTypes = []any{
	(*Merchant)(nil),                   // 0: merchant.Merchant
	(*MerchantOrder)(nil),              // 1: merchant.MerchantOrder
	(*CommonResponse)(nil),             // 2: merchant.CommonResponse
	(*MerchantRegisterRequest)(nil),    // 3: merchant.MerchantRegisterRequest
	(*MerchantRegisterResponse)(nil),   // 4: merchant.MerchantRegisterResponse
	(*MerchantLoginRequest)(nil),       // 5: merchant.MerchantLoginRequest
	(*MerchantLoginResponse)(nil),      // 6: merchant.MerchantLoginResponse
	(*GetMerchantInfoRequest)(nil),     // 7: merchant.GetMerchantInfoRequest
	(*GetMerchantInfoResponse)(nil),    // 8: merchant.GetMerchantInfoResponse
	(*UpdateMerchantInfoRequest)(nil),  // 9: merchant.UpdateMerchantInfoRequest
	(*AcceptOrderRequest)(nil),         // 10: merchant.AcceptOrderRequest
	(*RejectOrderRequest)(nil),         // 11: merchant.RejectOrderRequest
	(*ListMerchantOrdersRequest)(nil),  // 12: merchant.ListMerchantOrdersRequest
	(*ListMerchantOrdersResponse)(nil), // 13: merchant.ListMerchantOrdersResponse
}
var file_merchant_proto_depIdxs = []int32{
	0,  // 0: merchant.GetMerchantInfoResponse.merchant:type_name -> merchant.Merchant
	1,  // 1: merchant.ListMerchantOrdersResponse.orders:type_name -> merchant.MerchantOrder
	3,  // 2: merchant.MerchantService.MerchantRegister:input_type -> merchant.MerchantRegisterRequest
	5,  // 3: merchant.MerchantService.MerchantLogin:input_type -> merchant.MerchantLoginRequest
	7,  // 4: merchant.MerchantService.GetMerchantInfo:input_type -> merchant.GetMerchantInfoRequest
	9,  // 5: merchant.MerchantService.UpdateMerchantInfo:input_type -> merchant.UpdateMerchantInfoRequest
	10, // 6: merchant.MerchantService.AcceptOrder:input_type -> merchant.AcceptOrderRequest
	11, // 7: merchant.MerchantService.RejectOrder:input_type -> merchant.RejectOrderRequest
	12, // 8: merchant.MerchantService.ListMerchantOrders:input_type -> merchant.ListMerchantOrdersRequest
	4,  // 9: merchant.MerchantService.MerchantRegister:output_type -> merchant.MerchantRegisterResponse
	6,  // 10: merchant.MerchantService.MerchantLogin:output_type -> merchant.MerchantLoginResponse
	8,  // 11: merchant.MerchantService.GetMerchantInfo:output_type -> merchant.GetMerchantInfoResponse
	2,  // 12: merchant.MerchantService.UpdateMerchantInfo:output_type -> merchant.CommonResponse
	2,  // 13: merchant.MerchantService.AcceptOrder:output_type -> merchant.CommonResponse
	2,  // 14: merchant.MerchantService.RejectOrder:output_type -> merchant.CommonResponse
	13, // 15: merchant.MerchantService.ListMerchantOrders:output_type -> merchant.ListMerchantOrdersResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_merchant_proto_init() }
func file_merchant_proto_init() {
	if File_merchant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_proto_rawDesc), len(file_merchant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_proto_goTypes,
		DependencyIndexes: file_merchant_proto_depIdxs,
		MessageInfos:      file_merchant_proto_msgTypes,
	}.Build()
	File_merchant_proto = out.File
	file_merchant_proto_goTypes = nil
	file_merchant_proto_depIdxs = nil
}
