// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc2
// source: merchant.proto

package merchantProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MerchantService_MerchantRegister_FullMethodName   = "/merchant.MerchantService/MerchantRegister"
	MerchantService_MerchantLogin_FullMethodName      = "/merchant.MerchantService/MerchantLogin"
	MerchantService_GetMerchantInfo_FullMethodName    = "/merchant.MerchantService/GetMerchantInfo"
	MerchantService_UpdateMerchantInfo_FullMethodName = "/merchant.MerchantService/UpdateMerchantInfo"
	MerchantService_AcceptOrder_FullMethodName        = "/merchant.MerchantService/AcceptOrder"
	MerchantService_RejectOrder_FullMethodName        = "/merchant.MerchantService/RejectOrder"
	MerchantService_ListMerchantOrders_FullMethodName = "/merchant.MerchantService/ListMerchantOrders"
)

// MerchantServiceClient is the client API for MerchantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MerchantServiceClient interface {
	// 商家入驻（注册）
	MerchantRegister(ctx context.Context, in *MerchantRegisterRequest, opts ...grpc.CallOption) (*MerchantRegisterResponse, error)
	// 商家登录
	MerchantLogin(ctx context.Context, in *MerchantLoginRequest, opts ...grpc.CallOption) (*MerchantLoginResponse, error)
	// 获取商家信息
	GetMerchantInfo(ctx context.Context, in *GetMerchantInfoRequest, opts ...grpc.CallOption) (*GetMerchantInfoResponse, error)
	// 更新商家信息
	UpdateMerchantInfo(ctx context.Context, in *UpdateMerchantInfoRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	// 商家接单
	AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	// 商家拒单
	RejectOrder(ctx context.Context, in *RejectOrderRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	// 查询商家订单列表
	ListMerchantOrders(ctx context.Context, in *ListMerchantOrdersRequest, opts ...grpc.CallOption) (*ListMerchantOrdersResponse, error)
}

type merchantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantServiceClient(cc grpc.ClientConnInterface) MerchantServiceClient {
	return &merchantServiceClient{cc}
}

func (c *merchantServiceClient) MerchantRegister(ctx context.Context, in *MerchantRegisterRequest, opts ...grpc.CallOption) (*MerchantRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerchantRegisterResponse)
	err := c.cc.Invoke(ctx, MerchantService_MerchantRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) MerchantLogin(ctx context.Context, in *MerchantLoginRequest, opts ...grpc.CallOption) (*MerchantLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerchantLoginResponse)
	err := c.cc.Invoke(ctx, MerchantService_MerchantLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) GetMerchantInfo(ctx context.Context, in *GetMerchantInfoRequest, opts ...grpc.CallOption) (*GetMerchantInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMerchantInfoResponse)
	err := c.cc.Invoke(ctx, MerchantService_GetMerchantInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) UpdateMerchantInfo(ctx context.Context, in *UpdateMerchantInfoRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, MerchantService_UpdateMerchantInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, MerchantService_AcceptOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) RejectOrder(ctx context.Context, in *RejectOrderRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, MerchantService_RejectOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) ListMerchantOrders(ctx context.Context, in *ListMerchantOrdersRequest, opts ...grpc.CallOption) (*ListMerchantOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMerchantOrdersResponse)
	err := c.cc.Invoke(ctx, MerchantService_ListMerchantOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantServiceServer is the server API for MerchantService service.
// All implementations must embed UnimplementedMerchantServiceServer
// for forward compatibility.
type MerchantServiceServer interface {
	// 商家入驻（注册）
	MerchantRegister(context.Context, *MerchantRegisterRequest) (*MerchantRegisterResponse, error)
	// 商家登录
	MerchantLogin(context.Context, *MerchantLoginRequest) (*MerchantLoginResponse, error)
	// 获取商家信息
	GetMerchantInfo(context.Context, *GetMerchantInfoRequest) (*GetMerchantInfoResponse, error)
	// 更新商家信息
	UpdateMerchantInfo(context.Context, *UpdateMerchantInfoRequest) (*CommonResponse, error)
	// 商家接单
	AcceptOrder(context.Context, *AcceptOrderRequest) (*CommonResponse, error)
	// 商家拒单
	RejectOrder(context.Context, *RejectOrderRequest) (*CommonResponse, error)
	// 查询商家订单列表
	ListMerchantOrders(context.Context, *ListMerchantOrdersRequest) (*ListMerchantOrdersResponse, error)
	mustEmbedUnimplementedMerchantServiceServer()
}

// UnimplementedMerchantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantServiceServer struct{}

func (UnimplementedMerchantServiceServer) MerchantRegister(context.Context, *MerchantRegisterRequest) (*MerchantRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantRegister not implemented")
}
func (UnimplementedMerchantServiceServer) MerchantLogin(context.Context, *MerchantLoginRequest) (*MerchantLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantLogin not implemented")
}
func (UnimplementedMerchantServiceServer) GetMerchantInfo(context.Context, *GetMerchantInfoRequest) (*GetMerchantInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMerchantInfo not implemented")
}
func (UnimplementedMerchantServiceServer) UpdateMerchantInfo(context.Context, *UpdateMerchantInfoRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMerchantInfo not implemented")
}
func (UnimplementedMerchantServiceServer) AcceptOrder(context.Context, *AcceptOrderRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptOrder not implemented")
}
func (UnimplementedMerchantServiceServer) RejectOrder(context.Context, *RejectOrderRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectOrder not implemented")
}
func (UnimplementedMerchantServiceServer) ListMerchantOrders(context.Context, *ListMerchantOrdersRequest) (*ListMerchantOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMerchantOrders not implemented")
}
func (UnimplementedMerchantServiceServer) mustEmbedUnimplementedMerchantServiceServer() {}
func (UnimplementedMerchantServiceServer) testEmbeddedByValue()                         {}

// UnsafeMerchantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantServiceServer will
// result in compilation errors.
type UnsafeMerchantServiceServer interface {
	mustEmbedUnimplementedMerchantServiceServer()
}

func RegisterMerchantServiceServer(s grpc.ServiceRegistrar, srv MerchantServiceServer) {
	// If the following call pancis, it indicates UnimplementedMerchantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MerchantService_ServiceDesc, srv)
}

func _MerchantService_MerchantRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_MerchantRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantRegister(ctx, req.(*MerchantRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_MerchantLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).MerchantLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_MerchantLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).MerchantLogin(ctx, req.(*MerchantLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_GetMerchantInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).GetMerchantInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_GetMerchantInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).GetMerchantInfo(ctx, req.(*GetMerchantInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_UpdateMerchantInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMerchantInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).UpdateMerchantInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_UpdateMerchantInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).UpdateMerchantInfo(ctx, req.(*UpdateMerchantInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_AcceptOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).AcceptOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_AcceptOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).AcceptOrder(ctx, req.(*AcceptOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_RejectOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).RejectOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_RejectOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).RejectOrder(ctx, req.(*RejectOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_ListMerchantOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMerchantOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).ListMerchantOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_ListMerchantOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).ListMerchantOrders(ctx, req.(*ListMerchantOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantService_ServiceDesc is the grpc.ServiceDesc for MerchantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "merchant.MerchantService",
	HandlerType: (*MerchantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MerchantRegister",
			Handler:    _MerchantService_MerchantRegister_Handler,
		},
		{
			MethodName: "MerchantLogin",
			Handler:    _MerchantService_MerchantLogin_Handler,
		},
		{
			MethodName: "GetMerchantInfo",
			Handler:    _MerchantService_GetMerchantInfo_Handler,
		},
		{
			MethodName: "UpdateMerchantInfo",
			Handler:    _MerchantService_UpdateMerchantInfo_Handler,
		},
		{
			MethodName: "AcceptOrder",
			Handler:    _MerchantService_AcceptOrder_Handler,
		},
		{
			MethodName: "RejectOrder",
			Handler:    _MerchantService_RejectOrder_Handler,
		},
		{
			MethodName: "ListMerchantOrders",
			Handler:    _MerchantService_ListMerchantOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant.proto",
}
